# Generated by Django 6.0.5 on 2026-05-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(max_length=200)),
                ('perusahaan', models.CharField(max_length=200)),
                ('tipe', models.CharField(choices=[('kerja', 'Pengalaman Kerja'), ('organisasi', 'Organisasi'), ('volunteer', 'Volunteer'), ('magang', 'Magang / Internship')], default='kerja', max_length=20)),
                ('lokasi', models.CharField(blank=True, max_length=100)),
                ('mulai', models.DateField()),
                ('selesai', models.DateField(blank=True, help_text='Kosongkan jika masih berlangsung', null=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['urutan', '-mulai'],
            },
        ),
        migrations.CreateModel(
            name='PesanMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjek', models.CharField(blank=True, max_length=200)),
                ('pesan', models.TextField()),
                ('dikirim_at', models.DateTimeField(auto_now_add=True)),
                ('sudah_dibaca', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pesan Masuk',
                'verbose_name_plural': 'Pesan Masuk',
                'ordering': ['-dikirim_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nama_panggilan', models.CharField(blank=True, max_length=50)),
                ('tagline', models.CharField(help_text='Contoh: UI/UX Designer & Developer', max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('kota', models.CharField(blank=True, max_length=100)),
                ('negara', models.CharField(default='Indonesia', max_length=100)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('teknologi', models.CharField(blank=True, help_text='Pisah dengan koma, contoh: Python, Django, Bootstrap', max_length=300)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('url_live', models.URLField(blank=True, help_text='Link demo / website live')),
                ('url_github', models.URLField(blank=True, help_text='Link repository GitHub')),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('unggulan', models.BooleanField(default=False, help_text='Tampilkan sebagai proyek unggulan')),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ['urutan', '-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institusi', models.CharField(help_text='Nama universitas/sekolah', max_length=200)),
                ('jurusan', models.CharField(blank=True, max_length=200)),
                ('gelar', models.CharField(blank=True, help_text='Contoh: S.Kom, S.T.', max_length=100)),
                ('tahun_masuk', models.IntegerField()),
                ('tahun_lulus', models.IntegerField(blank=True, help_text='Kosongkan jika masih berlangsung', null=True)),
                ('deskripsi', models.TextField(blank=True, help_text='Prestasi, aktivitas, dll.')),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampil (0 = paling atas)')),
            ],
            options={
                'verbose_name': 'Riwayat Akademik',
                'verbose_name_plural': 'Riwayat Akademik',
                'ordering': ['urutan', '-tahun_masuk'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('technical', 'Technical / Hard Skills'), ('design', 'Design'), ('language', 'Language'), ('soft', 'Soft Skills'), ('tools', 'Tools & Software'), ('other', 'Lainnya')], default='technical', max_length=20)),
                ('level', models.PositiveIntegerField(default=80, help_text='Tingkat kemahiran 0–100 (ditampilkan sebagai progress bar)')),
                ('ikon', models.CharField(blank=True, help_text='Nama ikon Bootstrap Icons, contoh: bi-code-slash', max_length=100)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill',
                'ordering': ['kategori', 'urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='SosialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('email', 'Email'), ('twitter', 'Twitter / X'), ('other', 'Lainnya')], max_length=20)),
                ('url', models.CharField(help_text='URL lengkap atau alamat email, contoh: https://instagram.com/zahra', max_length=300)),
                ('tampil', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sosial Media',
                'verbose_name_plural': 'Sosial Media',
                'ordering': ['urutan'],
            },
        ),
    ]
