# Generated by Django 6.0.5 on 2026-05-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportofolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
