# Generated by Django 6.0.5 on 2026-05-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportofolio', '0002_remove_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url_github',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url_live',
        ),
        migrations.AddField(
            model_name='project',
            name='url_dokumentasi',
            field=models.URLField(blank=True, help_text='Link Dokumentasi'),
        ),
    ]
