# Generated by Django 6.0.5 on 2026-05-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportofolio', '0003_remove_project_url_github_remove_project_url_live_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
